services:
  redis:
    image: redis:latest
    platform: linux/amd64
    command: redis-server --requirepass default
    environment:
      REDIS_USER: default
      REDIS_PASSWORD: default
    ports:
      - "6379:6379"
    networks:
      - n8n-network

  waha:
    image: devlikeapro/waha:latest
    platform: linux/amd64
    environment:
      WHATSAPP_API_KEY: "6a35b8469d91432db7a896fc6e3dd4f2"
      WAHA_DASHBOARD_USERNAME: "admin"
      WAHA_DASHBOARD_PASSWORD: "123456"
      WHATSAPP_SWAGGER_USERNAME: "admin"
      WHATSAPP_SWAGGER_PASSWORD: "123456"
      WHATSAPP_HOOK_URL: http://n8n-teste:5678/webhook/webhook
      WHATSAPP_DEFAULT_ENGINE: GOWS
      WHATSAPP_HOOK_EVENTS: message
    volumes:
      - waha_sessions:/app/.sessions
      - waha_media:/app/.media
    ports:
      - "3003:3000"
    networks:
      - n8n-network

  n8n-teste:
    image: n8nio/n8n
    ports:
      - "5678:5678"
    volumes:
      - ./:/home/node/.n8n
    environment:
      WEBHOOK_URL: http://n8n-teste:5678
      N8N_HOST: n8n-teste
      GENERIC_TIMEZONE: "America/Sao_Paulo"
      N8N_LOG_LEVEL: debug
      N8N_COMMUNITY_PACKAGES_ALLOW_TOOL_USAGE: true
    restart: unless-stopped
    networks:
      - n8n-network

networks:
  n8n-network:
    driver: bridge

volumes:
  waha_sessions:
  waha_media:
